### ISSUE TITLE
Error when getting country (ipv6)

### ISSUE THREAD

**Issue by currychris** [sameera-madushan/COVID-19-STATS#1]
```
Traceback (most recent call last):
  File "COVID-19-STATS/stats.py", line 88, in <module>
    getCountry()
  File "COVID-19-STATS/stats.py", line 83, in getCountry
    search = re.search(r'Country: (.*)',result).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
In [line 81](https://github.com/sameera-madushan/COVID-19-STATS/blob/cf1aa59db5796e25aba4bcfa104460b4154ded5e/stats.py#L81) the api returns an error message when queried with an IPv6 address.

`error input invalid. enter IP address.`

In [line 83](https://github.com/sameera-madushan/COVID-19-STATS/blob/cf1aa59db5796e25aba4bcfa104460b4154ded5e/stats.py#L83) it crashes because the string is searched for `Country: (.*)` which is not in the error message.

**Comment by sameera-madushan** [comment]
Thanks
